server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  message: Hello User Service
