spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service?options=-c%20TimeZone=Asia/Ho_Chi_Minh
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  message: Hello User Service - DEV
